name: CD to S3

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'custom.css'
      - 'custom.css.map'
      - 'e-voice.scss'
  pull_request:
    branches: [ main ]
    paths:
      - 'custom.css'
      - 'custom.css.map'
      - 'e-voice.scss'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp custom.css s3://glamsci-website-styles/ --acl public-read --cache-control "public, max-age=120" --content-type  "text/css"
          aws s3 cp custom.css.map s3://glamsci-website-styles/ --acl public-read --cache-control "public, max-age=60" --content-type  "application/json"
          aws s3 cp e-voice.scss s3://glamsci-website-styles/ --acl public-read --cache-control "public, max-age=60" --content-type  "text/x-scss"
